# Generated by Django 6.0.6 on 2026-06-25 19:31

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, help_text='Укажите полное имя пользователя', max_length=150, verbose_name='Полное имя')),
                ('is_admin', models.BooleanField(default=False, help_text='Предоставляет доступ к административному интерфейсу', verbose_name='Администратор')),
                ('storage_path', models.CharField(help_text='Уникальный путь к директории пользователя на сервере', max_length=255, unique=True, verbose_name='Путь к хранилищу')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Обязательное. От 4 до 20 символов. Только латиница и цифры.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя должно начинаться с буквы, содержать только латинские буквы и цифры, и иметь длину от 4 до 20 символов.', regex='^[a-zA-Z][a-zA-Z0-9]{3,19}$')], verbose_name='Имя пользователя')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует.'}, max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='app_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='app_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Имя файла, указанное пользователем при загрузке', max_length=255, verbose_name='Оригинальное имя файла')),
                ('unique_name', models.CharField(help_text='Системное имя файла, под которым он хранится на сервере', max_length=255, unique=True, verbose_name='Уникальное имя файла')),
                ('file_path', models.CharField(help_text='Полный путь к файлу в файловой системе сервера', max_length=512, verbose_name='Путь к файлу')),
                ('file_size', models.BigIntegerField(default=0, help_text='Размер файла в байтах', verbose_name='Размер файла (байт)')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время, когда файл был загружен', verbose_name='Дата загрузки')),
                ('last_download_date', models.DateTimeField(blank=True, help_text='Дата и время последнего скачивания этого файла', null=True, verbose_name='Дата последнего скачивания')),
                ('comment', models.TextField(blank=True, help_text='Произвольный комментарий, добавленный пользователем', verbose_name='Комментарий')),
                ('public_link', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальная ссылка для скачивания файла', unique=True, verbose_name='Публичная ссылка')),
                ('user', models.ForeignKey(help_text='Пользователь, которому принадлежит этот файл', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
