# Generated by Django 6.0.6 on 2026-07-12 07:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=app.models.user_directory_path, verbose_name='Файл'),
        ),
    ]
